import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-white border-b">
          <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
            <a href="/" className="text-2xl font-semibold tracking-tight">NextAuthApp</a>
            <div className="nav-links">
              <a href="/" className="nav-link">Home</a>
              <a href="/login" className="nav-link">Login</a>
              <a href="/register" className="nav-link">Register</a>
              <a href="/dashboard" className="nav-link">Dashboard</a>
            </div>
          </div>
        </nav>

        <div className="bg-gradient-to-b from-white to-[var(--bg-2)] py-12">
          <main className="max-w-6xl mx-auto px-6">{children}</main>
        </div>
      </body>
    </html>
  );
}
